name: Conventional Commits

on: [pull_request]

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Commitsar check
        uses: aevea/commitsar@v0.16.0
