# Copyright (C) 2021 Casper Meijn <casper@meijn.net>
#
# SPDX-License-Identifier: CC0-1.0

name: Conventional Commits

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Commitsar check
        uses: aevea/commitsar@v0.16.0
